### ISSUE TITLE
Tooltipps translations will not work for added Lines in edit mode. 

### ISSUE THREAD

**Issue by RainerBielefeld** [Chaosmeister/DefinitionOfDone#10]
## STR: 
1. Test for existing DoD in a Task with one of the existing loclale (de_DE) 
   » Translation for all Icons will work 
2. Click "+" in last DoD-line to add a row  
   » new line appears
3. Hover mouse pointer over "Add row" icon in this line 
   * "Close Row" without translation, although translation does work for row above 😥

**Comment by Chaosmeister** [comment]
Can you create a pull request for your translator branch? Then I can try to reproduce it on my side.

As far as I can see, 'Close row' is not translated in your array, yet

https://github.com/RainerBielefeld/DefinitionOfDone/blob/main/Locale/de_DE/translations.php
