### ISSUE TITLE
Plugin not showing on list of plugins 

### ISSUE THREAD

**Issue by AverageDevOpsEnjoyer** [Chaosmeister/DefinitionOfDone#2]
Hello I tried installing the plugin for our kanboard but it doesn't appear on my list of plugins. Tried creating a local log file and it also returns an error message:

[critical] DefinitionOfDone: Unable to migrate schema for the plugin: DefinitionOfDone => SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'definition_of_done' already exists

**Comment by Chaosmeister** [comment]
Hey thanks for the report!
What database and version of kanboard do you use?

elijahobispo ***@***.***> schrieb am Di., 3. Okt. 2023, 10:17:

**Comment by elijahobispo** [comment]
Hello, we use kanboard version 1.2.32 and mysql 5.6. I also tried deleting the definition_of_done table and reinstalled the plugin but it still gives me the same error. Thank you!

**Comment by Chaosmeister** [comment]
I need to investigate a bit further.

I'm currently on vacation until Monday, I'll have a look at it then

**Comment by elijahobispo** [comment]
Okay got it. Will wait for further updates from you then, have a fun vacation! Thanks!

**Comment by aljawaid** [comment]
hey @elijahobispo 

Try this (in order):

1. Uninstall the plugin
2. delete the `definition_of_done` table in the database
3. delete the `definition_of_done` entry in the `plugin_schema_versions` table
4. Try installing again

**Comment by elijahobispo** [comment]
Hello, followed these steps and the results are still the same. The plugin still not showing on our list of plugins and is still receiving the table 'definition_of_done' error.

**Comment by Chaosmeister** [comment]
so I've set up a mariadb instance and installed my plugin without an issue

i'm not sure what happens on your end

**Comment by aljawaid** [comment]
> hey @elijahobispo
> 
> Try this (in order):
> 
>     1. Uninstall the plugin
> 
>     2. delete the `definition_of_done` table in the database
> 
>     3. delete the `definitionofdone` entry in the `plugin_schema_versions` table
> 
>     4. Try installing again

try again but swapping steps 3 and 4

**Comment by AverageDevOpsEnjoyer** [comment]
Hello, my apologies for the delayed response. I'll try aljawaid's steps on my end and let you guys know if it works. I'll also try installing mariadb instead of mysql just to see if that changes anything. Thank you!

**Comment by Chaosmeister** [comment]
heyo!

any updates over here?

**Comment by AverageDevOpsEnjoyer** [comment]
Hello, tried the previous steps given and still the results are the same, because of this we decided not to use the plugin instead since currently its not a must have on our end. Thank you very much for all the help guys!
