### ISSUE TITLE
Is it possible to show / check all TODO tasks in a general project view without having to open it?

### ISSUE THREAD

**Issue by djixas** [Chaosmeister/DefinitionOfDone#5]
![test](https://github.com/user-attachments/assets/1c966f2e-36fb-4c34-a4e8-a5fc34caa958)

Can't find a discussion forum here for plugin

**Comment by Chaosmeister** [comment]
Hi
A "check all" menu item might be useful

The preview might be a bit complicated though as the DOD can become arbitrarily long

**Comment by Chaosmeister** [comment]
I implemented this as a preview feature and I think I like it

**Comment by djixas** [comment]
> I implemented this as a preview feature and I think I like it

Oh wow, that's faster than the intercourse with my wife
