### ISSUE TITLE
Missing Locale

### ISSUE THREAD

**Issue by RainerBielefeld** [Chaosmeister/DefinitionOfDone#7]
I 
* created  new locale de_DE + de_DE_du 
* modified Plugin.php so that it will accept locale  
  
New branch or what shell we do?  
I also can deliver Spanish and French locale.

**Comment by Chaosmeister** [comment]
yeah, you can open a pull request if you like

**Comment by RainerBielefeld** [comment]
I created [this](https://github.com/RainerBielefeld/DefinitionOfDone) fork for adding my LOCALE changes.  
First tests with download of that version all successful.

Before Pull request I would like to integrate Translations for Tooltipps of  Missing Tooltipps #9
