### ISSUE TITLE
Missing Tooltipps

### ISSUE THREAD

**Issue by RainerBielefeld** [Chaosmeister/DefinitionOfDone#9]
for 
* Export icon
* Import icon  
* save Icon  

At least for my Installation:  

## My Configuration  
* Application version:  1.2.40 ,  installed at hoster [All-Inkl](https://all-inkl.com/)  
* PHP version: 8.3.8  
* PHP SAPI: fpm-fcgi  
* HTTP Client: cURL  
* OS Version: Linux 5.4.0-196-generic
* Database driver: mysql  
* Datenbank Version: 10.5.26-MariaDB-ubu2004-log
* Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:117.0a) Gecko/20100101 SeaMonkey/2.53.19, Build 20240329110002  
  
* Profile Language: German - DU
* [Plugins](https://kanboard.org/plugins.html):   
   * AgileIndicators 1.4.0
   * AutomaticActionUX 2.6.0
   * Broadcast 1.0.1  
   * Calendar 1.5.0
   * Customizer 1.14.2  
   * DefinitionOfDone 1.3.1 Master (Pivate version)
   * ~~[Global Search Plugin for Kanboard](https://github.com/kenlog/global-search-kanboard) 1.0.5~~ 
   * Group_assign 1.8.2
   * ~~KanboardSearchPlugin 1.1.0~~
   * MarkdownPlus 1.1.5
   * PasteImageToMarkdown  1.1.0
   * PluginManager  4.7.0
   * ProjectInvitation 1.0.0
   * Self-Registration  1.0.8  
   * SubtaskDescription 1.1.3
   * TagManager 1.6.0
   * Task2pdf  1.8.0
   * Wiki  	0.3.8

**Comment by Chaosmeister** [comment]
aye  that's an oversight
i'm gonna add em tomorrow

**Comment by RainerBielefeld** [comment]
If you create a Masster Branch I can 
* download that one 
* add Locale with Tooltipp Translations and modifications in plugins-php
* we do some tests
* Pull request.

Do you agree?

CU

Rainer

**Comment by Chaosmeister** [comment]
There already is a main branch

Usually you fork the repository, apply changes on your end and then open a pull request.

Then I can then review them, test if anything breaks on my end and approve them.

**Comment by Chaosmeister** [comment]
I just added the missing tooltips

'Import'
'Export'
'Save table'
